# read secrets.json
import json
from urllib.parse import quote_plus

with open("secrets.json", "r") as f:
    SECRETS = json.load(f)

PROJECT_NAME = SECRETS.get('PROJECT_NAME', 'EVENTS_IN_MINUTES')
HOST = SECRETS.get('HOST', '0.0.0.0')
PORT = SECRETS.get('PORT', 8000)
ENVIRONMENT = SECRETS.get('ENVIRONMENT', 'PROD')
DEBUG = False if ENVIRONMENT == 'PROD' else True

DATABASE_NAME = '_'.join([PROJECT_NAME.lower(), ENVIRONMENT.lower(), 'db'])
DATABASE_MAX_POOL_SIZE = SECRETS['DATABASE_MAX_POOL_SIZE']
DATABASE_URL = SECRETS['DATABASE_URL']
DATABASE_PORT = SECRETS['DATABASE_PORT']
JWT_TOKEN_EXPIRY_IN_DAYS = SECRETS['JWT_TOKEN_EXPIRY_IN_DAYS']
JWT_SECRET_KEY = SECRETS['JWT_SECRET_KEY']
JWT_ALGORITHM = SECRETS['JWT_ALGORITHM']

